#!/usr/bin/env python3

import os, argparse

parser = argparse.ArgumentParser()
parser.add_argument("--exclude", nargs='*')
args = parser.parse_args()

HOME = os.environ["HOME"]

with open("./modules-list", "r") as f:
    text = f.read().replace("~", HOME).replace("./", os.getcwd() + "/")
    for line in text.splitlines():
        if not line.startswith("#"):
            name, rest = line.split(": ")
            s_start, s_end = rest.split(" -> ")
            if args.exclude is None or name not in args.exclude:
                os.symlink(s_start, s_end)
